name: Build and push Docker image

on: [push]

env:
  IMAGE_NAME: playwright
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_ID=$(echo ghcr.io/${{ github.repository }}/$IMAGE_NAME | tr '[:upper:]' '[:lower:]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION

      # Authenticate with GitHub Packages registry
      - name: Authenticate with GitHub Packages registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Push the image to the registry
      - name: Push Docker image to GitHub Packages registry
        run: |
          docker push ghcr.io/karmacomputing/playwright-testing/playwright-testing:latest

