name: Build and push Docker image

on: [push]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t playwright-test

      # Authenticate with GitHub Packages registry
      - name: Authenticate with GitHub Packages registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Push the image to the registry
      - name: Push Docker image to GitHub Packages registry
        run: |
          docker push ghcr.io/karmacomputing/playwright-testing/playwright-testing:latest

