name: Playwright Container Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start container
      run: time docker run --rm -v $PWD/tests:/ms-playwright-agent/tests -v $PWD/:/src/app ghcr.io/karmacomputing/playwright-testing/playwright-testing:latest
