name: Playwright Container Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      playwright:
        name: 'Playwright Container Tests'
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/playwright:v1.29.0-focal
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: '3.11'
              cache: 'pip' # caching pip dependencies
          - uses: actions/setup-node@v3
            with:
              node-version: '18'
          - name: Install dependencies
            run: npm ci
          - name: Run your tests
            run: npx playwright test
